default: all

all: 1 2 3 4 5 6 7 8 9

1:
	gcc p1.c -o p1
	./p1
2:
	gcc p2.c -o p2
	./p2
3:
	gcc p3.c -o p3
	./p3
4:
	gcc p4.c -o p4
	./p4
5:
	gcc p5.c -o p5
	./p5
6:
	gcc p6.c -o p6
	./p6
7:
	gcc p7.c -o p7
	./p7
8:
	gcc p8.c -o p8
	./p8
9:
	gcc p9.c -o p9
	./p9
